//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставлено
    {
        public int НомерДоговора { get; set; }
        public string Товар { get; set; }
        public decimal Количество { get; set; }
        public decimal Цена { get; set; }
    
        public virtual Договоры Договоры { get; set; }
    }
}
